/**
 * Mock agent responses — realistic findings based on the sample auth diff.
 * Used when running with --mock flag (no API key needed).
 */

export const MOCK_RESPONSES = {
  security: {
    summary: 'Critical vulnerabilities found: SQL injection, hardcoded secrets, plain-text passwords, and sensitive data leakage.',
    findings: [
      {
        severity: 'critical',
        confidence: 0.98,
        file: 'src/routes/auth.js',
        line: 12,
        title: 'SQL Injection via string interpolation',
        description: 'User-controlled input `role` is directly interpolated into a SQL query string. An attacker can inject arbitrary SQL, dump the entire database, or escalate privileges.',
        suggestion: 'Use parameterized queries: db.query("SELECT * FROM users WHERE role = ?", [role])',
      },
      {
        severity: 'critical',
        confidence: 0.97,
        file: 'src/routes/auth.js',
        line: 34,
        title: 'Hardcoded JWT fallback secret',
        description: 'When JWT_SECRET env var is missing, the code silently falls back to "mysecretkey123". In any misconfigured or new environment, all tokens are signed with a known secret — making them trivially forgeable.',
        suggestion: 'Throw on missing secret: if (!process.env.JWT_SECRET) throw new Error("JWT_SECRET env var is required")',
      },
      {
        severity: 'high',
        confidence: 0.95,
        file: 'src/routes/auth.js',
        line: 38,
        title: 'Sensitive user data logged to console',
        description: 'console.log(JSON.stringify(user)) writes the full user object — including password hash — to stdout. In production this ends up in log aggregators visible to ops teams and third-party logging services.',
        suggestion: 'Log only safe fields: console.log("User logged in:", { id: user.id, email: user.email })',
      },
      {
        severity: 'critical',
        confidence: 0.96,
        file: 'src/routes/auth.js',
        line: 58,
        title: 'Passwords stored in plain text',
        description: 'User passwords are inserted directly into the database without hashing. A single DB breach exposes every user\'s password in cleartext.',
        suggestion: 'Hash before storing: const hashed = await bcrypt.hash(password, 12); then store hashed',
      },
      {
        severity: 'high',
        confidence: 0.91,
        file: 'src/routes/auth.js',
        line: 71,
        title: 'Response leaks full user object including password',
        description: 'res.json({ token, user: newUser }) returns the complete DB row to the client, including the password field.',
        suggestion: 'Destructure safe fields only: const { password, ...safeUser } = newUser; res.json({ token, user: safeUser })',
      },
    ],
  },

  performance: {
    summary: 'Two performance issues found: an N+1 query pattern and an O(n²) deduplication algorithm.',
    findings: [
      {
        severity: 'high',
        confidence: 0.94,
        file: 'src/routes/auth.js',
        line: 16,
        title: 'N+1 query — profile fetched per user in loop',
        description: 'db.query() is called inside a for...of loop over users. For 100 users this fires 101 DB queries. Under any real load this will saturate the DB connection pool.',
        suggestion: 'Fetch all profiles in one query and join in-memory: const profiles = await db.query("SELECT * FROM profiles WHERE user_id IN (?)", [userIds])',
      },
      {
        severity: 'medium',
        confidence: 0.88,
        file: 'src/routes/auth.js',
        line: 76,
        title: 'O(n²) deduplication — use a Set instead',
        description: 'Nested loops to find unique tags is O(n²). For a large posts table this becomes very slow. A Set reduces this to O(n).',
        suggestion: 'Replace with: const unique = [...new Set(tags.map(t => t.tag))]',
      },
      {
        severity: 'low',
        confidence: 0.72,
        file: 'src/routes/auth.js',
        line: 4,
        title: 'Entire lodash library imported for no apparent use',
        description: 'import _ from "lodash" adds ~70kb to the bundle but _ is never used in this file.',
        suggestion: 'Remove the unused import, or import only the function needed: import pick from "lodash/pick.js"',
      },
    ],
  },

  logic: {
    summary: 'Two definite bugs found: missing await causes auth bypass, and plain-text password comparison will always fail against hashed passwords.',
    findings: [
      {
        severity: 'critical',
        confidence: 0.99,
        file: 'src/routes/auth.js',
        line: 25,
        title: 'Missing await on async verifyToken — auth bypass',
        description: 'verifyToken() is async but called without await. It returns a Promise object, which is always truthy. Every request to /admin passes the auth check regardless of whether the token is valid or even present.',
        suggestion: 'Make the route handler async and await the call: const router = express.Router(); router.get("/admin", async (req, res) => { const valid = await verifyToken(token); ... })',
      },
      {
        severity: 'high',
        confidence: 0.93,
        file: 'src/routes/auth.js',
        line: 36,
        title: 'Plain-text password comparison',
        description: 'user.password === password compares a raw string against whatever is in the DB. If passwords were ever hashed (the correct state), login will always fail. If they\'re plain-text, this is a security hole.',
        suggestion: 'Use: await bcrypt.compare(password, user.password)',
      },
      {
        severity: 'medium',
        confidence: 0.85,
        file: 'src/routes/auth.js',
        line: 49,
        title: 'No input validation — null inputs reach the database',
        description: 'email, password, name are destructured from req.body with no validation. If any are undefined or null, the INSERT query may fail silently or store null values.',
        suggestion: 'Validate inputs first: if (!email || !password || !name) return res.status(400).json({ error: "All fields are required" })',
      },
    ],
  },

  architecture: {
    summary: 'The register endpoint violates Single Responsibility — it handles validation, hashing, DB writes, token generation, and response formatting in one function.',
    findings: [
      {
        severity: 'medium',
        confidence: 0.87,
        file: 'src/routes/auth.js',
        line: 46,
        title: 'Register route has too many responsibilities',
        description: 'The /register handler does input validation, duplicate checking, password hashing (missing), DB insertion, token generation, and response formatting. This makes it hard to test, reuse, or change any one concern.',
        suggestion: 'Extract into service layer: authService.register(email, password, name) handles DB + hashing; route handler only calls service and formats response.',
      },
      {
        severity: 'low',
        confidence: 0.76,
        file: 'src/routes/auth.js',
        line: 34,
        title: 'JWT secret logic duplicated in three places',
        description: 'process.env.JWT_SECRET || "mysecretkey123" appears three times. Any change requires updating multiple locations.',
        suggestion: 'Extract to a module-level constant or config: const JWT_SECRET = process.env.JWT_SECRET (and throw if missing)',
      },
    ],
  },

  tests: {
    summary: 'No tests present for any of the new endpoints — /admin, /register, and the enriched /users route are completely untested.',
    coverage: 'poor',
    findings: [
      {
        severity: 'high',
        confidence: 0.95,
        file: 'src/routes/auth.js',
        line: 22,
        title: 'No test for /admin auth bypass vulnerability',
        description: 'The /admin route has a critical auth bug (missing await) with no test to catch it. A regression test would have caught this immediately.',
        suggestion: 'Add test: it("should reject requests without a valid token", async () => { const res = await request(app).get("/admin"); expect(res.status).toBe(403); })',
      },
      {
        severity: 'high',
        confidence: 0.92,
        file: 'src/routes/auth.js',
        line: 46,
        title: 'No tests for /register endpoint',
        description: 'The entire register flow — duplicate email check, DB insertion, token generation — has zero test coverage.',
        suggestion: 'Add tests for: successful registration, duplicate email rejection, missing fields, and that the response does not include the password field.',
      },
      {
        severity: 'medium',
        confidence: 0.83,
        file: 'src/routes/auth.js',
        line: 10,
        title: 'No test for SQL injection in /users route',
        description: 'The role query parameter is directly interpolated into SQL with no test verifying input sanitization.',
        suggestion: 'Add test: pass role="admin\' OR \'1\'=\'1" and assert it does not return all users.',
      },
    ],
  },

  judge: {
    verdict: 'BLOCK',
    score: 18,
    summary: 'This PR must not be merged. It introduces an authentication bypass that grants every user admin access, stores passwords in plain text, and has a SQL injection vulnerability. These are not theoretical risks — they are exploitable in production as written. All critical findings must be resolved before this can proceed.',
    agentSummaries: {
      security: 'Critical: SQL injection, hardcoded secret, plain-text password storage, sensitive data logged and leaked in responses',
      performance: 'N+1 query on user fetch, O(n²) tag deduplication, unused lodash import',
      logic: 'Auth bypass via missing await (every /admin request passes), plain-text password comparison, no input validation',
      architecture: 'Register route violates SRP, JWT secret duplicated three times across the file',
      tests: 'Zero test coverage on all three new endpoints including the critical auth bypass route',
    },
    findings: [
      {
        severity: 'critical',
        confidence: 0.99,
        agents: ['logic', 'security'],
        quorum: true,
        file: 'src/routes/auth.js',
        line: 25,
        title: 'Auth bypass — missing await makes every /admin request succeed',
        description: 'verifyToken() is async but called without await, returning a truthy Promise. Every request to /admin passes regardless of token validity.',
        suggestion: 'Add async to route handler and await verifyToken(token)',
      },
      {
        severity: 'critical',
        confidence: 0.98,
        agents: ['security'],
        quorum: false,
        file: 'src/routes/auth.js',
        line: 12,
        title: 'SQL injection via role query parameter',
        description: 'Raw string interpolation of user input into SQL query allows full database compromise.',
        suggestion: 'Use parameterized query: db.query("SELECT * FROM users WHERE role = ?", [role])',
      },
      {
        severity: 'critical',
        confidence: 0.97,
        agents: ['security', 'logic'],
        quorum: true,
        file: 'src/routes/auth.js',
        line: 58,
        title: 'Passwords stored and compared in plain text',
        description: 'Plain-text password storage means a single DB breach exposes every user credential.',
        suggestion: 'Hash with bcrypt: bcrypt.hash(password, 12) on register, bcrypt.compare() on login',
      },
      {
        severity: 'critical',
        confidence: 0.97,
        agents: ['security'],
        quorum: false,
        file: 'src/routes/auth.js',
        line: 34,
        title: 'Hardcoded JWT fallback secret',
        description: 'Fallback to "mysecretkey123" means tokens can be forged in any environment missing the env var.',
        suggestion: 'Throw if JWT_SECRET is not set — never fall back to a hardcoded value',
      },
      {
        severity: 'high',
        confidence: 0.95,
        agents: ['performance'],
        quorum: false,
        file: 'src/routes/auth.js',
        line: 16,
        title: 'N+1 query in /users route',
        description: 'One DB query per user in a loop. Fetch all profiles in a single IN query instead.',
        suggestion: 'const profiles = await db.query("SELECT * FROM profiles WHERE user_id IN (?)", [userIds])',
      },
      {
        severity: 'high',
        confidence: 0.95,
        agents: ['security'],
        quorum: false,
        file: 'src/routes/auth.js',
        line: 38,
        title: 'Sensitive data logged and leaked in API response',
        description: 'Full user object including password written to logs and returned in register response.',
        suggestion: 'Strip sensitive fields before logging or returning: const { password, ...safeUser } = user',
      },
      {
        severity: 'medium',
        confidence: 0.85,
        agents: ['logic'],
        quorum: false,
        file: 'src/routes/auth.js',
        line: 49,
        title: 'No input validation on register endpoint',
        description: 'Null or undefined inputs pass straight to the database with no validation.',
        suggestion: 'Validate all required fields before processing the request',
      },
    ],
  },
};

export function getMockAgentResult(agentName) {
  return MOCK_RESPONSES[agentName] ?? { findings: [], summary: 'No findings.' };
}
